import type {Locale} from '@/lib/i18n';
import {slugify} from '@/lib/utils';

const categoryLabels: Record<string, {en: string; zh: string}> = {
  'Life OS': {en: 'Life OS', zh: '人生操作系统'},
  'World Models': {en: 'World Models', zh: '世界模型'},
  'Methods and Judgment': {en: 'Methods and Judgment', zh: '方法与判断'},
  'Learning and Growth': {en: 'Learning and Growth', zh: '学习与成长'},
  Life: {en: 'Life', zh: '人生'},
  Career: {en: 'Career', zh: '职场'},
  'People and Leadership': {en: 'People and Leadership', zh: '人物与领导力'},
  'Company Research': {en: 'Company Research', zh: '公司研究'},
  Education: {en: 'Education', zh: '教育'},
  'Resource Allocation': {en: 'Resource Allocation', zh: '投入'},
  'AI and Technology': {en: 'AI and Technology', zh: 'AI 与技术'},
  Civilization: {en: 'Civilization', zh: '文明'}
};

const tagLabels: Record<string, {en: string; zh: string}> = {
  AI: {en: 'AI', zh: '人工智能'},
  Analysis: {en: 'Analysis', zh: '分析'},
  'AI Tools': {en: 'AI Tools', zh: 'AI 工具'},
  Artifacts: {en: 'Artifacts', zh: '作品'},
  Assessment: {en: 'Assessment', zh: '评价'},
  'Business Model': {en: 'Business Model', zh: '商业模式'},
  'Capability Boundary': {en: 'Capability Boundary', zh: '能力边界'},
  'Capability Compounding': {en: 'Capability Compounding', zh: '能力复利'},
  'Capital Allocation': {en: 'Capital Allocation', zh: '资本配置'},
  Career: {en: 'Career', zh: '职业'},
  'Career Development': {en: 'Career Development', zh: '职场成长'},
  'Case Analysis': {en: 'Case Analysis', zh: '案例分析'},
  Civilization: {en: 'Civilization', zh: '文明'},
  Community: {en: 'Community', zh: '社区'},
  'Company Culture': {en: 'Company Culture', zh: '企业文化'},
  Compatibility: {en: 'Compatibility', zh: '兼容性'},
  'Competitive Moat': {en: 'Competitive Moat', zh: '竞争壁垒'},
  'Cognitive Compound Interest': {en: 'Cognitive Compound Interest', zh: '认知复利'},
  'Cognitive Models': {en: 'Cognitive Models', zh: '认知模型'},
  'Compound Interest': {en: 'Compound Interest', zh: '复利效应'},
  Compounding: {en: 'Compounding', zh: '复利'},
  Consumption: {en: 'Consumption', zh: '消费观'},
  Creativity: {en: 'Creativity', zh: '创造力'},
  Curiosity: {en: 'Curiosity', zh: '好奇心'},
  Curriculum: {en: 'Curriculum', zh: '课程'},
  'Decision Making': {en: 'Decision Making', zh: '决策思维'},
  'Depth vs Breadth': {en: 'Depth vs. Breadth', zh: '深度与广度'},
  'Developer Ecosystem': {en: 'Developer Ecosystem', zh: '开发者生态'},
  Education: {en: 'Education', zh: '教育'},
  'Education Case Studies': {en: 'Education Case Studies', zh: '教育案例库'},
  'Education Philosophy': {en: 'Education Philosophy', zh: '教育哲学'},
  'Education Practice': {en: 'Education Practice', zh: '教育实践'},
  'Education Resources': {en: 'Education Resources', zh: '教育资源'},
  'Education Stages': {en: 'Education Stages', zh: '教育阶段'},
  'Education Trends': {en: 'Education Trends', zh: '教育趋势'},
  'Emotional Management': {en: 'Emotional Management', zh: '情绪管理'},
  Entrepreneurship: {en: 'Entrepreneurship', zh: '创业'},
  Essence: {en: 'Essence', zh: '本质'},
  Environment: {en: 'Environment', zh: '环境'},
  Exercise: {en: 'Exercise', zh: '运动'},
  'Family Education': {en: 'Family Education', zh: '家庭教育'},
  Family: {en: 'Family', zh: '家庭'},
  'Family Affection': {en: 'Family Affection', zh: '亲情'},
  'Family Cases': {en: 'Family Cases', zh: '家庭案例'},
  'Family Wealth': {en: 'Family Wealth', zh: '家庭财富'},
  'First-Principles Thinking': {en: 'First-Principles Thinking', zh: '第一性原理'},
  'First Principles': {en: 'First Principles', zh: '第一性原理'},
  Feedback: {en: 'Feedback', zh: '反馈'},
  Focus: {en: 'Focus', zh: '专注'},
  Freedom: {en: 'Freedom', zh: '自由'},
  Friendship: {en: 'Friendship', zh: '友情'},
  'Great Companies': {en: 'Great Companies', zh: '伟大公司'},
  'Great People': {en: 'Great People', zh: '关键人物'},
  Growth: {en: 'Growth', zh: '成长'},
  'Growth Environment': {en: 'Growth Environment', zh: '成长环境'},
  'Growth Path': {en: 'Growth Path', zh: '成长路径'},
  Habits: {en: 'Habits', zh: '习惯'},
  'Individual Difference': {en: 'Individual Difference', zh: '个体差异'},
  Interest: {en: 'Interest', zh: '兴趣'},
  'Inversion Thinking': {en: 'Inversion Thinking', zh: '逆向思维'},
  Iteration: {en: 'Iteration', zh: '迭代'},
  'Knowledge Compound Interest': {en: 'Knowledge Compound Interest', zh: '知识复利'},
  'Knowledge Foundation': {en: 'Knowledge Foundation', zh: '知识底座'},
  Leadership: {en: 'Leadership', zh: '领导力'},
  'Learning Framework': {en: 'Learning Framework', zh: '学习成长框架'},
  Life: {en: 'Life', zh: '人生'},
  'Life Case Studies': {en: 'Life Case Studies', zh: '人生案例库'},
  'Life Philosophy': {en: 'Life Philosophy', zh: '人生哲学'},
  'Life OS': {en: 'Life OS', zh: '人生操作系统'},
  'Life Positioning': {en: 'Life Positioning', zh: '人生定位'},
  'Life Review': {en: 'Life Review', zh: '人生复盘'},
  'Life Strategy': {en: 'Life Strategy', zh: '人生策略'},
  'Life Turning Point': {en: 'Life Turning Point', zh: '人生转折'},
  'Lifelong Learning': {en: 'Lifelong Learning', zh: '终身学习'},
  'Long-Term Strategy': {en: 'Long-Term Strategy', zh: '长期战略'},
  'Long-Term Capability': {en: 'Long-Term Capability', zh: '长期能力'},
  'Long-Term Trust': {en: 'Long-Term Trust', zh: '长期信任'},
  'Long-Termism': {en: 'Long-Termism', zh: '长期主义'},
  Love: {en: 'Love', zh: '爱情'},
  Happiness: {en: 'Happiness', zh: '幸福'},
  Health: {en: 'Health', zh: '健康'},
  'Health and Growth': {en: 'Health and Growth', zh: '健康与成长'},
  Infrastructure: {en: 'Infrastructure', zh: '基础设施'},
  Judgment: {en: 'Judgment', zh: '判断'},
  Meaning: {en: 'Meaning', zh: '意义'},
  'Mental Models': {en: 'Mental Models', zh: '思维模型'},
  'AI Learning': {en: 'AI Learning', zh: 'AI 学习'},
  'Independent Thinking': {en: 'Independent Thinking', zh: '独立思考'},
  Marriage: {en: 'Marriage', zh: '婚姻'},
  'Marriage and Family': {en: 'Marriage and Family', zh: '婚姻与家庭'},
  'Major Life Decisions': {en: 'Major Life Decisions', zh: '人生重大决策'},
  'Margin of Safety': {en: 'Margin of Safety', zh: '安全边际'},
  Motivation: {en: 'Motivation', zh: '动机'},
  Patience: {en: 'Patience', zh: '耐心'},
  'Parent-Child Relationship': {en: 'Parent-Child Relationship', zh: '亲子关系'},
  'People Cases': {en: 'People Cases', zh: '人物案例'},
  'Positive Loop': {en: 'Positive Loop', zh: '正循环'},
  'Psychological Resilience': {en: 'Psychological Resilience', zh: '心理韧性'},
  'Reality Calibration': {en: 'Reality Calibration', zh: '现实校准'},
  'Organizational Learning': {en: 'Organizational Learning', zh: '组织学习'},
  'Operating System': {en: 'Operating System', zh: '操作系统'},
  'Parent-Child Communication': {en: 'Parent-Child Communication', zh: '亲子沟通'},
  'Path Design': {en: 'Path Design', zh: '路径设计'},
  'Personal Growth': {en: 'Personal Growth', zh: '个人成长'},
  'Self Awareness': {en: 'Self Awareness', zh: '自我认知'},
  'Self Knowledge': {en: 'Self Knowledge', zh: '自知'},
  Relationships: {en: 'Relationships', zh: '关系经营'},
  Sleep: {en: 'Sleep', zh: '睡眠'},
  'Personalized Education': {en: 'Personalized Education', zh: '因材施教'},
  'Personalized Learning': {en: 'Personalized Learning', zh: '个性化学习'},
  'Platform Strategy': {en: 'Platform Strategy', zh: '平台战略'},
  Practice: {en: 'Practice', zh: '实践'},
  'Problem Decomposition': {en: 'Problem Decomposition', zh: '问题拆解'},
  'Product Strategy': {en: 'Product Strategy', zh: '产品战略'},
  'Project-Based Learning': {en: 'Project-Based Learning', zh: '项目制学习'},
  'Public Narrative': {en: 'Public Narrative', zh: '公共叙事'},
  Review: {en: 'Review', zh: '复盘'},
  Responsibility: {en: 'Responsibility', zh: '责任'},
  'Role Models': {en: 'Role Models', zh: '榜样'},
  'Self Discipline': {en: 'Self Discipline', zh: '自律'},
  'Social Environment': {en: 'Social Environment', zh: '社会环境'},
  'Social Network': {en: 'Social Network', zh: '社交关系'},
  'Spiritual Wealth': {en: 'Spiritual Wealth', zh: '精神财富'},
  Strengths: {en: 'Strengths', zh: '优势'},
  'Systems Thinking': {en: 'Systems Thinking', zh: '系统思维'},
  'T-Shaped Talent': {en: 'T-Shaped Talent', zh: 'T 型人才'},
  'Talent Development': {en: 'Talent Development', zh: '人才培养'},
  Talent: {en: 'Talent', zh: '天赋'},
  'Technology Trend': {en: 'Technology Trend', zh: '技术趋势'},
  'Trade-Offs': {en: 'Trade-Offs', zh: '取舍'},
  'Value Exchange': {en: 'Value Exchange', zh: '价值交换'},
  Value: {en: 'Value', zh: '价值'},
  Wealth: {en: 'Wealth', zh: '财富'},
  'Wealth and Happiness': {en: 'Wealth and Happiness', zh: '财富与幸福'},
  Weaknesses: {en: 'Weaknesses', zh: '短板'},
  'Asset Allocation': {en: 'Asset Allocation', zh: '资产配置'},
  'Big Company': {en: 'Big Company', zh: '大公司'},
  Business: {en: 'Business', zh: '企业'},
  'Business Ownership': {en: 'Business Ownership', zh: '企业所有权'},
  'Career Case Studies': {en: 'Career Case Studies', zh: '职场案例库'},
  'Career Decision': {en: 'Career Decision', zh: '职业决策'},
  'Career Growth': {en: 'Career Growth', zh: '职业成长'},
  'Career Operating System': {en: 'Career Operating System', zh: '职场操作系统'},
  'Career Path': {en: 'Career Path', zh: '职业路径'},
  'Career Philosophy': {en: 'Career Philosophy', zh: '职业认知'},
  'Career Planning': {en: 'Career Planning', zh: '职业规划'},
  'Career Review': {en: 'Career Review', zh: '职场复盘'},
  'Cash Flow': {en: 'Cash Flow', zh: '现金流'},
  Collaboration: {en: 'Collaboration', zh: '协作'},
  Communication: {en: 'Communication', zh: '沟通能力'},
  'Company Cases': {en: 'Company Cases', zh: '企业案例'},
  Depth: {en: 'Depth', zh: '深度'},
  ETF: {en: 'ETF', zh: 'ETF'},
  'Entrepreneurial Capability': {en: 'Entrepreneurial Capability', zh: '创业能力'},
  'Entrepreneurship Prerequisites': {en: 'Entrepreneurship Prerequisites', zh: '创业前提'},
  'High-Value Roles': {en: 'High-Value Roles', zh: '高价值岗位'},
  'Interview Review': {en: 'Interview Review', zh: '面试复盘'},
  'Learning Ability': {en: 'Learning Ability', zh: '学习能力'},
  Management: {en: 'Management', zh: '管理'},
  'Management Thinking': {en: 'Management Thinking', zh: '管理思想'},
  Optionality: {en: 'Optionality', zh: '选择权'},
  'Organizational Capability': {en: 'Organizational Capability', zh: '组织能力'},
  'Professional Capability': {en: 'Professional Capability', zh: '专业能力'},
  'Professional Depth': {en: 'Professional Depth', zh: '专业深耕'},
  'Project Experience': {en: 'Project Experience', zh: '项目经验'},
  'Project Review': {en: 'Project Review', zh: '项目复盘'},
  'Promotion Review': {en: 'Promotion Review', zh: '晋升复盘'},
  'Real Estate': {en: 'Real Estate', zh: '房地产'},
  Risk: {en: 'Risk', zh: '风险'},
  'Risk Management': {en: 'Risk Management', zh: '风险管理'},
  'Skill Development': {en: 'Skill Development', zh: '技能提升'},
  Startup: {en: 'Startup', zh: '小公司'},
  'Company Shares': {en: 'Company Shares', zh: '公司份额'},
  'Value Creation': {en: 'Value Creation', zh: '价值创造'},
  'World Models': {en: 'World Models', zh: '世界模型'}
};

function labelFromFallback(value: string, locale: Locale) {
  if (locale === 'en') {
    return value;
  }

  return value;
}

export function getCategoryLabel(category: string, locale: Locale) {
  return categoryLabels[category]?.[locale] ?? labelFromFallback(category, locale);
}

export function getTagLabel(tag: string, locale: Locale) {
  return tagLabels[tag]?.[locale] ?? labelFromFallback(tag, locale);
}

export function getCategoryHref(category: string, locale: Locale) {
  return `/${locale}/categories/${slugify(category)}/`;
}

export function getTagHref(tag: string, locale: Locale) {
  return `/${locale}/tags/${slugify(tag)}/`;
}
